### ISSUE TITLE
ListBox Items duplicate in logical tree. 

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/Avalonia#10246]
I noticed that after migrating to preview5, ListBox no longer wraps items in container. Is this an expected behavior? 
Also every child element is attached to logical tree twice. 

![image](https://user-images.githubusercontent.com/14807942/217138378-7fe77e68-f6dd-43b7-b487-23ad52bfa242.png)

**Comment by rabbitism** [comment]
Oh, I figured out the container issue. Will try to fix. 
Please help to check the duplicate logical tree children issue.

**Comment by grokys** [comment]
Fixed by #10247 I assume.

**Comment by rabbitism** [comment]
@grokys, Hi, I think the duplication issue is still not fixed. Is it expected? There are only two items set in code but for in logical tree.

**Comment by grokys** [comment]
Ah ok, I will reopen.
