### ISSUE TITLE
Text issues

### ISSUE THREAD

**Issue by danielmayost** [AvaloniaUI/Avalonia#11448]
I think #8070 is no longer maintainable and can be closed, anyhow I will mention some issues that have not been fixed yet:
- Selection problems in blended text (input: `אבגדה 12345 ABCDEF אבגדה`) in both FlowDirection mode, (happens mainly when you select with the mouse from the end to the beginning).
- Double clicking on the above input will not select the correct word.
- Selecting with the keyboard arrows is completely messed up with the above input.
- In RTL mode, type `A` then space, the letter A will go out of bounds:
![image](https://github.com/AvaloniaUI/Avalonia/assets/41772276/90450db8-6d0d-48e8-a625-69efd1de1c6b)
- in ItemsRepeater tab, The text exceeds the limits of the right (in RTL mode):
![image](https://github.com/AvaloniaUI/Avalonia/assets/41772276/993cf4ba-78ca-47a7-af3d-325ed2c9a20f)

cc @Gillibald

**Comment by Gillibald** [comment]
It seems even Chrome/Edge can't deal with that sequence but I will have a look

**Comment by danielmayost** [comment]
ok, but even the `ABC אבגדה` input not working (from end to beginning).

**Comment by robloo** [comment]
The below issue previously occurred several previews ago and then was fixed. Now it's back. Text measurement within tooltips doesn't work.

Too much margin/padding:
![image](https://github.com/AvaloniaUI/Avalonia/assets/17993847/87386e40-0296-40c8-874d-54fea9763e73)

Cutting off last character:
![image](https://github.com/AvaloniaUI/Avalonia/assets/17993847/a96c8e45-a12c-4692-bb09-d55034f54581)

**Comment by Gillibald** [comment]
@danielmayost https://github.com/AvaloniaUI/Avalonia/pull/11532

**Comment by danielmayost** [comment]
#11532 does fix most of the problems.

Still not works:
- [**RTL**] the `אבג ABC אבג 123` sequence:

Avalonia:
![Animation](https://github.com/AvaloniaUI/Avalonia/assets/41772276/da723264-e6d9-4d61-9289-ef7160912ec6)

Notepad:
![Animation](https://github.com/AvaloniaUI/Avalonia/assets/41772276/d351eaf4-dded-4c3c-81fd-15ab69427c06)

- Selecting with the keyboard arrows still not works correctly, try to select the above sequence from start to end then from end to start, it doesn't even respond at the end:
![Animation](https://github.com/AvaloniaUI/Avalonia/assets/41772276/9ca9a22a-d62b-47be-9907-ac7f81e213e7)


A bit of a regression:
- In an empty right-aligned TextBox, the cursor placed on the left side until you type any character.
- [**RTL**] Sometimes enters an infinite loop, a bit hard to reproduce but here is one: in 'Custom selection brush' TextBox (ControlCatalog) try to select the `אבג ABC` sequence: 
![Animation](https://github.com/AvaloniaUI/Avalonia/assets/41772276/e4171369-12cb-449b-a359-5566de986455)
- [**RTL**] [Multiline TextBox] the cursor does not move a line after the sequence 'ab':
![Animation](https://github.com/AvaloniaUI/Avalonia/assets/41772276/e1605673-aa4b-436f-af42-9bac98c8e78b)

**Comment by Gillibald** [comment]
Next step to fix these issues will be setting selection ranges manually via SelectionStart/End to be able to write unit tests.

**Comment by Gillibald** [comment]
@robloo I would need a minimal repro to be able to fix the Popup issue
