### ISSUE TITLE
Binding RotateTransform (and probably other transforms) to a value doesn't work

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaUI/Avalonia#11639]
**Describe the bug**
When we try to bind RotateTransform.Angle via styles it doesn't work:
```
<Setter Property="RotateTransform.Angle" Value="{TemplateBinding MyValue}" />
```
But, for example, animation works:
```
<Animation Duration="0:0:1.2" IterationCount="INFINITE">
  <KeyFrame Cue="0%">
    <Setter Property="RotateTransform.Angle" Value="0" />
  </KeyFrame>
  <KeyFrame Cue="50%">
    <Setter Property="RotateTransform.Angle" Value="100" />
  </KeyFrame>
  <KeyFrame Cue="60%">
    <Setter Property="RotateTransform.Angle" Value="200" />
  </KeyFrame>
  <KeyFrame Cue="100%">
    <Setter Property="RotateTransform.Angle" Value="300" />
  </KeyFrame>
</Animation>
```
And simple value works:
```
<Setter Property="RotateTransform.Angle" Value="30" />
```

**To Reproduce**

1. Create custom control
2. Add a property
3. Animate a property
4. Try to add setter and bind RotateTransform.Angle to that property

**Expected behavior**
RotateTransform.Angle should be binded to property

- Version: 11.0.0-rc1.1

**Comment by maxkatz6** [comment]
It probably was fixed in the latest master. Can you check?

**Comment by SKProCH** [comment]
It still reproduceable in `11.0.999-cibuild0036132-beta` and `11.0.999-cibuild0036125-beta` (from https://github.com/AvaloniaUI/Avalonia/pull/11638)

**Comment by rabbitism** [comment]
I have a feeling that this is the general issue of mine https://github.com/AvaloniaUI/Avalonia/issues/10567
