### ISSUE TITLE
Changing color of SolidColorBrush don't cause a rerender

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaUI/Avalonia#11673]
**Describe the bug**
When i change `Color` property of `SolidColorBrush` in resources it doesn't cause a rerender. It works in 11-preview*, but doesn't work in rc1-1

**To Reproduce**
1. App.axaml:
  ```xaml
  <Application.Resources>
      <SolidColorBrush x:Key="MyBrush" Color="Aqua"></SolidColorBrush>
  </Application.Resources>
  ```
2. Window:
  ```xaml
  <StackPanel>
    <TextBlock Foreground="{DynamicResource MyBrush}">TEST TEXT</TextBlock>
    <Button Foreground="{DynamicResource MyBrush}" Click="Button_OnClick">CHANGE COLOR</Button>
    <Button Foreground="{DynamicResource MyBrush}">DUMMY</Button>
  </StackPanel>
  ```
3. Code behind:
  ```csharp
  private void Button_OnClick(object? sender, RoutedEventArgs e) {
      var solidColorBrush = App.Current.Resources["MyBrush"] as SolidColorBrush;
      var random = new Random();
      solidColorBrush.Color = Color.FromRgb((byte)random.Next(0, 255), (byte)random.Next(0, 255), (byte)random.Next(0, 255));
  }
  ```
![e138723d-ab24-444d-9a71-e9d02e862599](https://github.com/AvaloniaUI/Avalonia/assets/29896317/aa720669-7e52-48ac-9b11-5a5d0d5ba428)

**Desktop (please complete the following information):**
- Version: 11.0.0-rc1.1

Fast repro (also contains my other code, don't mind): 
[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/11665158/AvaloniaApplication1.zip)

**Comment by danipen** [comment]
Probably related (or duplicated) to #11036.

**Comment by SKProCH** [comment]
Yes, i think it related to your issue, @danipen

But i facing this issue only for rc1-1, not for preview*. I should check it again.

**Comment by workgroupengineering** [comment]
if you change the code like this

```csharp
        private void Button_OnClick(object? sender, RoutedEventArgs e)
        {
            var random = new Random();
            App.Current!.Resources["MyBrush"] = new SolidColorBrush()
            {
                Color = Color.FromRgb((byte)random.Next(0, 255), (byte)random.Next(0, 255), (byte)random.Next(0, 255))
            };
        }
```

works.

**Comment by maxkatz6** [comment]
I think it's more related to this https://github.com/AvaloniaUI/Avalonia/issues/11640 one and was already fixed in master.

**Comment by SKProCH** [comment]
@maxkatz6 I've tried the `11.0.999-cibuild0036218-beta` and its partially fixed. But, for example, button foreground still doesn't get an update:  
![f02eb481-d5f4-4f64-841f-03745fb8aeb2](https://github.com/AvaloniaUI/Avalonia/assets/29896317/fc7f2e87-7fcc-49be-a15d-8b5a1de3d617)

**Comment by SKProCH** [comment]
Seems like this issue strikes back in https://github.com/AvaloniaCommunity/Material.Avalonia/issues/262

Update for Avalonia 11.0.0: still reproduceable as in my last comment. Here is an updated code: [AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/12008706/AvaloniaApplication1.zip)

But i figured out some interesting details, if we put a control with a explicit binding **after** the button, button color changing start working. 
```xaml
<StackPanel>
  <Button Foreground="{DynamicResource MyBrush}" Click="Button_OnClick">CHANGE COLOR</Button>
  <Button Foreground="{DynamicResource MyBrush}">DUMMY</Button>
  <TextBlock Foreground="{DynamicResource MyBrush}">TEST TEXT</TextBlock>
</StackPanel>
```

But, if we put another button in the end 😆, it doesn't work:
```xaml
<StackPanel>
  <Button Foreground="{DynamicResource MyBrush}" Click="Button_OnClick">CHANGE COLOR</Button>
  <Button Foreground="{DynamicResource MyBrush}">DUMMY</Button>
  <TextBlock Foreground="{DynamicResource MyBrush}">TEST TEXT</TextBlock>
  <Button Foreground="{DynamicResource MyBrush}">DUMMY</Button>
</StackPanel>
```
![image](https://github.com/AvaloniaUI/Avalonia/assets/29896317/f6c7d819-4854-4941-8f3b-58df01ed88e5)

@kekekeks, @maxkatz6 i think what it's something compositor related, do you think?

**Comment by SKProCH** [comment]
Also, non of this were updated in previewer, may be this  info will help:  
![image](https://github.com/AvaloniaUI/Avalonia/assets/29896317/de8b06a7-f88c-448b-b7ad-0e058eefcfac)
