### ISSUE TITLE
ViewLocator.Build called unnecessarily

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#12189]
In v11.0.0

I got this ListBox, displaying FileItem objects.

I'm explicitly specifying the DataTemplate.

```
<ListBox ItemsSource="{Binding Files.Source}" x:CompileBindings="False"
         SelectedItem="{Binding Files.CurrentItem, Mode=TwoWay}" TabIndex="8" Background="{x:Null}">
    <ListBox.Styles>
        <Style Selector="ListBoxItem">
            <Setter Property="TabIndex" Value="5" />
        </Style>
    </ListBox.Styles>
    <ListBox.ItemTemplate>
        <DataTemplate>
            <TextBlock Text="{Binding Display}">
                <Interaction.Behaviors>
                    <RoutedEventTriggerBehavior RoutedEvent="{x:Static InputElement.DoubleTappedEvent}">
                        <InvokeCommandAction
                            Command="{Binding ViewModel.Play, RelativeSource={RelativeSource AncestorType=views:MainView}}"
                            CommandParameter="{x:Null}" />
                    </RoutedEventTriggerBehavior>
                </Interaction.Behaviors>
            </TextBlock>
        </DataTemplate>
    </ListBox.ItemTemplate>
</ListBox>
```

For each item **except the first ones visible on startup**, it calls ViewLocator.Build on the FileItem, which throws a NotFoundException and returns a TextBox with Not Found text; which doesn't get displayed at all.

This doesn't affect the output, but this behavior is strange. Particularly that it affects only items coming into view from scrolling, and not the first displayed items.

**Comment by arnirichard** [comment]
I have just upgraded my project to Avalonia 11. I have a `ListBox` and I am setting `ItemsSource`. `ViewLocator.Build` is called with the viewmodel object as parameter and throws error in `Activator.CreateInstance(type)` (see below). If I comment out that part of Build and just turn `TextBlock` then my application runs. I am wondering if this is related?

```
System.MissingMethodException: 'Cannot dynamically create an instance of type 'MessageFolder'. Reason: No parameterless constructor defined.'
```

**Comment by workgroupengineering** [comment]
> MessageFolder

Your `MessageFolder` class has no zero parameter constructor.

**Comment by arnirichard** [comment]
If I add parameterless constructor to MessageFolder then I get this exception:
```
System.InvalidCastException: 'Unable to cast object of type 'YedaMail.MessageFolder' to type 'Avalonia.Controls.Control'.'
```
I don't know why it is constructing viewmodel objects. This did not happen before Avalonia 11.

**Comment by alexanderdeman** [comment]
I'm having the same issue after upgrading to v11. 

In my situation I have a couple of CheckBoxes which filter the values in a ComboBox. The state of these CheckBoxes is persisted between program runs. When starting the application everything works (the filter is applied), but after unchecking a box it calls the Build method of the ViewLocator when I try to expand the ComboBox. This fails because of the missing default constructor.

**Comment by timunie** [comment]
@alexanderdeman please file a minimal sample to reproduce

**Comment by alexanderdeman** [comment]
@timunie I've spent several hours trying to create a sample, but so far no luck. My sample application keeps working without issues and I don't know why. I'm going to try to strip my application to see if I can provide you with a sample that way. That might take a while though...

@mysteryx93 @arnirichard are you able to provide a minimal sample?

**Comment by timunie** [comment]
I have the feeling this is either fixed in latest version or there is something complex going on the ViewModel. Does the project having the issue use same version as the sample you tried to build?

**Comment by alexanderdeman** [comment]
Yes, both are using 11.0.4. Could it be that a blank project created with v11 behaves differently compared to an upgraded v0.10 project?

**Comment by timunie** [comment]
We had countless changes, so there is a huge chance this behaves differently. For example CompiledBindings can now enabled by default while you had to opt in in 0.10.x

**Comment by mysteryx93** [comment]
I tried again in my app, no error is thrown. Looks like the issue has been fixed.

**Comment by timunie** [comment]
Closing this as it seems to be fixed acc to feedback. If someone has a reliable way to reproduce please ping me and I'll reopen the issue.

**Comment by baaron4** [comment]
This issue is still present but now happening to ComboBox on Avalonia 11.1.4. Tested with an without Compile Bindings.

It always trips this exception the moment I start scrolling in an open combobox. Its attempting to create my model empty, so I gave it a empty cast option but this error still comes up.

`System.InvalidCastException: 'Unable to cast object of type 'MyApp.Models.MyModel' to type 'Avalonia.Controls.Control'.'`
![image](https://github.com/user-attachments/assets/7dceb6bd-38bc-4b64-b4ed-47297b4ce5d4)

**Comment by baaron4** [comment]
I have to manually check for these models used in ComboBoxes now and filter them out on my ViewLocator


```
            if (type != null && type.FullName !=  "MyApp.Models.MyModel")
            {
                return (Control)Activator.CreateInstance(type)!;
            }
            else
            {
            return new TextBlock { Text = "Not Found: " + name };
            }
```

**Comment by BlackDawnX** [comment]
This issue is still present but now happening to ListBox on Avalonia 11.3.0
