### ISSUE TITLE
Mica on Windows 11 22621.1992 does not work with certain desktop wallpaper

### ISSUE THREAD

**Issue by chmckay** [AvaloniaUI/Avalonia#12237]
**Describe the bug**
I have a triple monitor Windows 11 system. I was initially thinking this was related to my GPUs, but cycling the desktop wallpaper between my monitors can cause the issue to move from monitor to monitor.

Specifically, when the the window is not focused on some wallpapers, there is no blurring of the background whatsoever (see the attached screenshot). When the window is focused, I see strange artifacts like solid blocks underneath some elements in spots, partially blurred segments and ghosted text. When I drag the window, the Mica zone flickers and flashes the wallpaper through the window. Windows dragged over the area occasionally leave artifacts about 100 pixels below the window being dragged. Taking a screenshot with the Windows Snipping tool yield the transparency issue. Using Print Screen renders the window as I would expect, so I took a photo with my phone (sorry for the quality).

I've double checked that I'm up-to-date on my drivers (Intel and nVidia). As a note, AcrylicBlur seems to work perfectly on everything. Since it appears to be wallpaper related, I'm not sure what I can add to that, other than provide copies of some of the wallpapers I'm using. Interestingly, this works perfectly on some wallpapers. Two of my monitors are connected to the Intel GPU and the third is connected to an nVidia T1200. I had initially thought it was the T1200, but when I changed wallpapers on that monitor, the issue disappeared. That same wallpaper displayed on a different monitor exhibited the same issue. Since Mica samples the desktop wallpaper and doesn't just blur, I can kind of understand why it's reliant on the wallpaper, but I don't understand why some wallpapers cause the issue. As an FYI, I use a combination of HD and 4k wallpapers, which are primarily nature photos.

**To Reproduce**

1. Create a new Avalonia app with Avalonia 11.0.0
2. Set the transparency hint to Mica, AcrylicBlur, Blur on the main window
3. Create the recommended <panel> with an embedded ExperimentalAcrylicBorder embedded in it (using code from [here](https://docs.avaloniaui.net/docs/tutorials/music-store-app/creating-a-modern-looking-window)

**Expected behavior**
I'd like the Mica to render properly on Windows 11 devices.

**Screenshots**
Unfocused window
![Unfocused Window](https://github.com/AvaloniaUI/Avalonia/assets/7585810/27f5b73e-f28f-4250-93a1-246ccc6888b0)

Focused window immediately after being dragged
![20230717_142127](https://github.com/AvaloniaUI/Avalonia/assets/7585810/a99485fd-3d59-4a0b-8c37-e64391c3e495)

Both screenshots are running the same executable (with the transparency hint set to Mica,AcrylicBlur,Blue), just moved between monitors

**Desktop (please complete the following information):**
HP zBook Studio 15.6
11th Gen Intel i7-11850H
32GB RAM
1TB NVME
Builtin monitor: 1920x1080, 100% scaling (Intel GPU), 60.16Hz
External monitor 1: (my primary) is 1920x1200, 100% scaling (Intel GPU), 59.95Hz
External monitor 2: 1920x1080, 100% scaling (nVidia T1200 GPU), 60Hz

- OS: [e.g. Windows, Mac, Linux (State distribution)]
Windows 11 Pro 22621.1992 x64
.Net 7

**Additional context**
As mentioned above, AcrylicBlur works perfectly on this machine. It's just the Mica that's failing

**Comment by maxkatz6** [comment]
> Specifically, when the the window is not focused on some wallpapers, there is no blurring of the background whatsoever

It sounds like typical behavior for acrylic in UWP apps. And expected there. Not for Mica though.

Do you have the same issue with WinUI or UWP apps that use Mica?

**Comment by chmckay** [comment]
I'm about to upgrade to 11.1. Has this been addressed in that build?

**Comment by timunie** [comment]
@chmckay give it a try sure. But the issue is open and has the help wanted tag, so likely not fixed. If you have an idea how to do, a PR is welcome 🤗
