### ISSUE TITLE
DataGrid can't select/edit rows where an element match other element Equality

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#13894]
## Describe the bug
When a `DataGrid` have two or more rows with same content that match the `Equals` with `true` against the other element, those can't be selected nor edited. This behavior persists since I remember at least (Avalonia 0.10).
I guess that DataGrid is using equality instead references which is causing the problem. This cause serious problem when you want to add a new row for user to editing, if user add two rows they will be identical and expect him to modify data after all, but he can't because only first distinct row can be selected/edited.
This prevents us from implement `IEquality` on classes, since will cause the problem. If equality is not implemented, ie: `Equals` DataGrid works as expected with classes, and threat them by reference.

## To Reproduce

This can be easily reproduced by use a simple list of Integers, since 1 == 1 only first distinct element is clickable/editable.

```C#
public List<int> Tester => new List<int>(){1, 1, 1, 1, 2, 2, 2, 3};
```

```xaml
        <DataGrid Name="TestGrid"
                  BorderBrush="Gray"
                  BorderThickness="1"
                  MinWidth="720"
                  MinHeight="400"
                  GridLinesVisibility="Horizontal"
                  IsReadOnly="False"
                  SelectionMode="Extended"
                  ClipboardCopyMode="IncludeHeader"
                  ItemsSource="{Binding Tester}">
            <DataGrid.Columns>
                <DataGridTextColumn Header="Number" Binding="{Binding}"/>
            </DataGrid.Columns>
        </DataGrid>

```
## Expected behavior
All rows to be selectable and editable regardless they match other row equality or not

## Screenshots

https://github.com/AvaloniaUI/Avalonia/assets/113281/99fe1d2b-0b25-4ebb-99c3-92275e2fe6e6

## Environment 

- OS: Windows 11
- Avalonia-Version: 11.0.6

**Comment by maxkatz6** [comment]
Was it also fixed by https://github.com/AvaloniaUI/Avalonia/pull/13845?

**Comment by timunie** [comment]
I don't think so. We have the same issue if you want to select the same string in a ListBox for example. Iirc you cannot select these idividually.

**Comment by ionite34** [comment]
Still an issue in 11.1.3 and 11.2.0-beta1.

Record types with compiler `IEquatable` interfaces that are equal also causes add items to be ignored and existing duplicates to be not editable when adding a default object as new row.
