### ISSUE TITLE
How to fix DataGridHeader style

### ISSUE THREAD

**Issue by ntprohd** [AvaloniaUI/Avalonia#14052]
## Describe the bug
Separator of DataGridColumnHeader will clipped by header bound.

## Screenshots
![Screenshot_1](https://github.com/AvaloniaUI/Avalonia/assets/28997276/0a009259-4c99-4719-be15-b94bfe65a187)

## Environment 

- OS: [ Windows]
- Avalonia-Version: [11.0.5 or 11.0.6]

## Code
```c#
<DataGrid Grid.Row="0" IsReadOnly="True" CornerRadius="3"
					  ItemsSource="{Binding Offers}"
					  GridLinesVisibility="All"
					  AutoGenerateColumns="False"
					  BorderThickness="1"
					  BorderBrush="Gray"
					  HorizontalAlignment="Stretch">
				<DataGrid.Resources>
					<x:Double x:Key="DataGridSortIconMinWidth">0</x:Double>
				</DataGrid.Resources>
				<DataGrid.Columns>
					<DataGridTextColumn Header="Name" Width="*" Binding="{Binding Name}"/>
					<DataGridTextColumn Header="Link" Width="*" Binding="{Binding Link}"/>
					<DataGridTextColumn Header="Limit" Width="*" Binding="{Binding Limit}"/>
					<DataGridTextColumn Header="Thread" Width="*" Binding="{Binding Thread}"/>
					<DataGridTextColumn Header="Delay" Width="*" Binding="{Binding Delay}"/>
					<DataGridTextColumn Header="User Agent" Width="*" Binding="{Binding UserAgent}"/>
					<DataGridTextColumn Header="Tools" Width="*" Binding="{Binding Tools}"/>
					<DataGridTextColumn Header="Proxy" Width="*" Binding="{Binding Proxy}"/>
					<DataGridTextColumn Header="Language" Width="*" Binding="{Binding Language}"/>
					<DataGridTextColumn Header="Referrer" Width="*" Binding="{Binding Referrer}"/>
					<DataGridTextColumn Header="Auto Start" Width="*" Binding="{Binding TimeAutoStart}"/>
					<DataGridTextColumn Header="Auto Stop" Width="*" Binding="{Binding TimeAutoStop}"/>
					<DataGridCheckBoxColumn Header="Auto Fake" Width="*" Binding="{Binding AutoFake}"/>
					<DataGridTextColumn Header="Network" Width="*" Binding="{Binding Network}"/>
					<DataGridTextColumn Header="Running" Width="*" Binding="{Binding Running}"/>
					<DataGridTextColumn Header="Success" Width="*" Binding="{Binding Success}"/>
					<DataGridTemplateColumn Header="Start" Width="*">
						<DataGridTemplateColumn.CellTemplate>
							<DataTemplate>
								<Button Content="Start" Margin="2" Background="{Binding BgStart}" Foreground="{Binding FgStart}" Command="{Binding ((vm:MainWindowViewModel)DataContext).StartOfferCommand, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Window}}}" CommandParameter="{Binding}" HorizontalAlignment="Stretch" HorizontalContentAlignment="Center"></Button>
							</DataTemplate>
						</DataGridTemplateColumn.CellTemplate>
					</DataGridTemplateColumn>
					<DataGridTemplateColumn Header="Stop" Width="*" >
						<DataGridTemplateColumn.CellTemplate>
							<DataTemplate>
								<Button Content="Stop" Margin="2" Background="{Binding BgStop}" Foreground="{Binding FgStop}" Command="{Binding ((vm:MainWindowViewModel)DataContext).StopOfferCommand, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Window}}}" CommandParameter="{Binding}" HorizontalAlignment="Stretch" HorizontalContentAlignment="Center"></Button>
							</DataTemplate>
						</DataGridTemplateColumn.CellTemplate>
					</DataGridTemplateColumn>
					<DataGridTemplateColumn Header="Edit" Width="*" >
						<DataGridTemplateColumn.CellTemplate>
							<DataTemplate x:DataType="vm:MainWindowViewModel">
								<Button Content="Edit" Margin="2" Command="{Binding ((vm:MainWindowViewModel)DataContext).EditOfferCommand, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Window}}}" CommandParameter="{Binding}" HorizontalAlignment="Stretch" HorizontalContentAlignment="Center"></Button>
							</DataTemplate>
						</DataGridTemplateColumn.CellTemplate>
					</DataGridTemplateColumn>
					<DataGridTemplateColumn Header="Delete" Width="*" >
						<DataGridTemplateColumn.CellTemplate>
							<DataTemplate x:DataType="vm:MainWindowViewModel">
								<Button Content="Delete" Margin="2" Command="{Binding ((vm:MainWindowViewModel)DataContext).DeleteOfferCommand, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Window}}}" CommandParameter="{Binding}" HorizontalAlignment="Stretch" HorizontalContentAlignment="Center"></Button>
							</DataTemplate>
						</DataGridTemplateColumn.CellTemplate>
					</DataGridTemplateColumn>
				</DataGrid.Columns>
</DataGrid>

```

**Comment by thevortexcloud** [comment]
It's probably worth mentioning what theme you are using.

**Comment by ntprohd** [comment]
> It's probably worth mentioning what theme you are using.

i am using FluentTheme

**Comment by RentonIssac** [comment]
web had same issue here.

**Comment by maxkatz6** [comment]
I think it was already fixed on nightly builds. Can somebody check?

**Comment by RentonIssac** [comment]
Not fixed yet in version: 11.0.9
I didn't  see any commit about this issue by now.

**Comment by timunie** [comment]
@maxkatz6 it's still present in case you use `Width="*"`. Tested using nightly.

**Comment by RentonIssac** [comment]
bump

**Comment by RentonIssac** [comment]
it's still present. Tested using nightly.

**Comment by dif-sam** [comment]
As possible workaround, you may set property `UseLayoutRounding` to `False` in the style for `DataGridColumnHeader`.
