### ISSUE TITLE
CompiledBinding fails to compile with error AVLN:9999

### ISSUE THREAD

**Issue by ChernyshevDS** [AvaloniaUI/Avalonia#14273]
## Describe the bug
I have a project based on Avalonia MVVM template using ReactiveUI targeting net6 with compiled bindings enabled on project level.
This project contains a viewModel, containing `ReactiveCommand`. I'm trying to create a binding to `ReactiveCommand.IsExecuting` of type `IObservable<bool>` in xaml, but the project fails to compile with the following error:

> Avalonia error AVLN:9999: Member 'System.IObservable`1' is declared in another module and needs to be imported

I've created a minimal reproduction project, see the attachment. [avalonia-xaml-bug.zip](https://github.com/AvaloniaUI/Avalonia/files/13987748/avalonia-xaml-bug.zip)

## To Reproduce
1. Create a project based on Avalonia.Mvvm template with ReactiveUI
2. Add a ReactiveCommand to MainWindowViewModel
3. Try to create a binding in view like:

```
<TextBox IsEnabled="{Binding !MyCoolCommand.IsExecuting^}" />
```

## Expected behavior
Compilation should not have errors.

## Environment 

- OS: Windiws 10 Pro 19045.3930
- Avalonia-Version: 11.0.6
- IDE: Visual Studio Community 2022 17.8.1

**Comment by stevemonaco** [comment]
I'm not sure if `CompiledBinding` supports the stream binding operator for observables. Maybe a maintainer can comment.

If not, the easiest workaround is to use reflection: `IsEnabled="{ReflectionBinding !ReloadCommand.IsExecuting^}"`

Another option is to bind this yourself in code-behind, though this approach involves naming controls.

```cs
    public partial class MainWindow : ReactiveWindow<MainWindowViewModel>
    {
        public MainWindowViewModel ViewModel => (MainWindowViewModel)DataContext!;

        public MainWindow()
        {
            InitializeComponent();
        }

        protected override void OnDataContextChanged(EventArgs e)
        {
            base.OnDataContextChanged(e);
            textBox.Bind(IsEnabledProperty, ViewModel.ReloadCommand.IsExecuting); // I skipped the negation
        }
    }
```

**Comment by maxkatz6** [comment]
Yes, it should support that. Potentially fixed by https://github.com/AvaloniaUI/Avalonia/pull/13970

**Comment by stevemonaco** [comment]
I still get the compile-time error on the latest commit (11.1.999-cibuild0043628-beta) for that PR.

**Comment by sinatrocious** [comment]
> Potentially fixed by #13970

Is this PR released or not yet?

I am using Avalonia 11.0.10 and getting compile error. With `ReflectionBinding` no problems.

How can I see from which version merged PR is available? I open PR, remember the date of merging, then go to [tags](https://github.com/AvaloniaUI/Avalonia/tags), find tag with later date and it will be there, right? Means #13970 should be in [11.0.8](https://github.com/AvaloniaUI/Avalonia/releases/tag/11.0.8), but why I can't find this PR number on that page, nor [here](https://github.com/AvaloniaUI/Avalonia/releases)?

**Comment by timunie** [comment]
11.1 beta hsa it in but not 11.0.10

**Comment by jp2masa** [comment]
> How can I see from which version merged PR is available? I open PR, remember the date of merging, then go to [tags](https://github.com/AvaloniaUI/Avalonia/tags), find tag with later date and it will be there, right? Means #13970 should be in [11.0.8](https://github.com/AvaloniaUI/Avalonia/releases/tag/11.0.8), but why I can't find this PR number on that page, nor [here](https://github.com/AvaloniaUI/Avalonia/releases)?

@sinatrocious You should look for the merge commit:

![merge](https://github.com/AvaloniaUI/Avalonia/assets/10765201/689122a0-aa76-489f-98f5-e5807caeb89b)

> Merged via the queue into master with commit [3b1eb33](https://github.com/AvaloniaUI/Avalonia/commit/3b1eb338e61c6ef8223a9f0d123d390289fa6e49)

Then open the link, and the tags that contain the commit should appear:

![commit](https://github.com/AvaloniaUI/Avalonia/assets/10765201/b4a50add-8f41-45c5-9f49-133cfd5ff72e)

In this case, it's only 11.1.0-beta1.

**Comment by sinatrocious** [comment]
@jp2masa, an amazing guide with pictures, thanks!

**Comment by timunie** [comment]
Can anyone confirm it's solved in 11.1 beta?

**Comment by stevemonaco** [comment]
I don't know the area well, but seems fixed to me on 11.1-beta1. The following builds and runs as expected with compiled bindings on:

```cs
public class MainWindowViewModel : ViewModelBase
{
    public IObservable<bool> IsEvenTimer { get; } = Observable.Interval(TimeSpan.FromSeconds(1))
        .Repeat()
        .Select(x => x % 2 == 0);
}
```

```xml
<StackPanel>
    <TextBlock Text="{Binding IsEvenTimer^}" />
    <TextBlock Text="{Binding !IsEvenTimer^}" />
</StackPanel>
```

**Comment by BobbyCannon** [comment]
Repo project that demonstrates the issue. https://github.com/BobbyCannon/BugProjects,

Open the AvaloniaBindingIssues.sln and build, it'll fail. If you move the CustomList.cs from [ClassLibrary] back into back into the [AvaloniaBindingIssues] project then it'll build.
