### ISSUE TITLE
[11.1-beta2] Regression: Window System buttons is not visible when `ExtendClientAreaToDecorationsHint="True"`

### ISSUE THREAD

**Issue by baochenw** [AvaloniaUI/Avalonia#15908]
### Describe the bug

This is a regression of 11.1-beta2. The issue is not reproducible with 11.1-beta1.
When set `ExtendClientAreaToDecorationsHint="True"` to MainWindow, the window system buttons (Minimize, Maximize and Close button) are not visible and the window has no border and can't drag move.

### To Reproduce

1. Set `ExtendClientAreaToDecorationsHint="True"` on MainWindow
2. Build and start app, the the window system buttons (Minimize, Maximize and Close button) are not visible and the window has no border and can't drag move.
3. Remove `ExtendClientAreaToDecorationsHint="True"`, the title bar appears.
4. Keep `ExtendClientAreaToDecorationsHint="True"` and downgrade to 11.1-beta1, the issue is gone.

### Expected behavior

The same behavior to 11.1-beta1

### Avalonia version

11.1-beta2

### OS

Windows

**Comment by rabbitism** [comment]
Should have been fixed by https://github.com/AvaloniaUI/Avalonia/pull/15552. Can you please verify in latest master?

**Comment by baochenw** [comment]
Close it as it has already fixed by #15552

**Comment by guilhermeolisi** [comment]
I am experiencing the same issue in Avalonia 11.1.2. Will the fix for this issue be included in version 11.1.3?

**Comment by malex81** [comment]
> Will the fix for this issue be included in version 11.1.3?
No. Error still reproduced in 11.1.3. Last working wersion is 11.0.13.
