### ISSUE TITLE
IActivatableLifetime Activated event not firing

### ISSUE THREAD

**Issue by amasidlovermedoc** [AvaloniaUI/Avalonia#16403]
### Describe the bug

Following the document [here](https://docs.avaloniaui.net/docs/concepts/services/activatable-lifetime) and having read issue #15316 and noting that the feature is in beta - I've started to see if I can use app links. However, although the link seems to register and opens my app the Activated event is never triggered.

### To Reproduce

In my app's MainActivity I have added a 'using' for Android.Content and then added the following intent filter:
```
[IntentFilter(
    new string[] { Intent.ActionView },
    Categories = new[] { Intent.CategoryDefault, Intent.CategoryBrowsable },
    DataScheme = "zymlink",
    AutoVerify = true)]   
public class MainActivity : AvaloniaMainActivity<App>
{
```
This does correctly generate the AndroidManifest.xml entries.

In my App.axaml.cs I have then added:
```
        if (Application.Current!.TryGetFeature(typeof(IActivatableLifetime)) is { } activatableLifetime)
        {
            _logger.LogInformation("Attaching event for incoming URIs.");

            ((IActivatableLifetime)activatableLifetime).Activated += (s, a) =>
           {
                _logger.LogInformation("Activation event detected a: {a} s: {s}",a,s);
               if (a is ProtocolActivatedEventArgs protocolArgs && protocolArgs.Kind == ActivationKind.OpenUri)
               {
                   if (_logger is not null)
                   {
                       _logger.LogInformation("App activated via Uri: {Uri}", protocolArgs.Uri);
                   }
               }
           };
        }
```
In my Initialize() method.

I have then compiled the app and tested its core functionality and that it loads etc. then issued:

```adb shell am start -d "zymlink://testing" -W -a android.intent.action.VIEW ```

(note I also tried adding the 'package' but the behaviour is identical).

The response to the adb shell command is
```
[Mon Jul 22 14:37:16] amasidlover@madai ~/Downloads $  adb shell am start -d "zymlink://testing" -W -a android.intent.action.VIEW
Starting: Intent { act=android.intent.action.VIEW dat=zymlink://testing/... }
Status: ok
LaunchState: COLD
Activity: com.CompanyName.ZymonicApp/crc6419625b4a03cd00f0.MainActivity
TotalTime: 4899
WaitTime: 4902
Complete
[Mon Jul 22 14:37:58] amasidlover@madai ~/Downloads $  adb shell am start -d "zymlink://testing" -W -a android.intent.action.VIEW
Starting: Intent { act=android.intent.action.VIEW dat=zymlink://testing/... }
Warning: Activity not started, intent has been delivered to currently running top-most instance.
Status: ok
LaunchState: UNKNOWN (0)
Activity: com.CompanyName.ZymonicApp/crc6419625b4a03cd00f0.MainActivity
TotalTime: 0
WaitTime: 2
Complete
```

I have NLog configured to send my logs to logcat and grepping that for my App identifier shows:
```
07-22 14:02:04.416 22742 22742 I ZymonicApp: Attaching event for incoming URIs.
07-22 14:02:04.942 22742 22742 D ZymonicApp: "MainWindowViewModel" handleAuthenticationChange Running on thread "1"
```
and then when I run the intent:
```
07-22 15:39:00.659   560   573 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=zymlink://testing/... flg=0x10000000 cmp=com.CompanyName.ZymonicApp/crc6419625b4a03cd00f0.MainActivity} with LAUNCH_MULTIPLE from uid 2000 (BAL_ALLOW_PERMISSION) result code=3
```

### Expected behavior

However, I never see the 'Activation event detected...' or 'App activated via Uri: ...' appear in the logcat output. 

### Avalonia version

11.1.0-rc2

### OS

Android

### Additional context

The intent filter definitely seems to be working; the adb logcat output shows the intent being passed to my app - and my app gets brought to the foreground if I have the emulator with something else in the foreground. However, the Activated event doesn't seem to fire.

Have I missed a set-up step in my app somewhere?

**Comment by maxkatz6** [comment]
Fixed by https://github.com/AvaloniaUI/Avalonia/pull/16477

**Comment by amasidlovermedoc** [comment]
I've tried various 11.0 and 11.1 versions including 11.1.0 and 11.1.3 - but still get exactly the same results as above. Is there a working example app that I could look at to see if I can see what I'm doing wrong? I still suspect its some configuration aspect but not sure exactly what...

**Comment by amasidlovermedoc** [comment]
I'm now part of the way there - I was playing with OnCreate in MainActivity.cs to see if that gave me any idea what was going on and at some point in the testing discovered that the intent only causes an activation event if the app is not in the foreground.

However, I am not quite there yet. If I send the intent when the app is not running I get:

```
08-30 13:28:57.172  8788  8788 I ZymonicApp: Activation event detected a: Avalonia.Controls.ApplicationLifetimes.ProtocolActivatedEventArgs s: Avalonia.Android.Platform.AndroidActivatableLifetime
08-30 13:28:57.173  8788  8788 I ZymonicApp: App activated via Uri: zymlink://testing/uri
08-30 13:28:57.179  8788  8788 I ZymonicApp: Activation event detected a: Avalonia.Controls.ApplicationLifetimes.ActivatedEventArgs s: Avalonia.Android.Platform.AndroidActivatableLifetime
```

But f the app is in the background (and running) I only get
```
08-30 13:29:24.947  8788  8788 I ZymonicApp: Activation event detected a: Avalonia.Controls.ApplicationLifetimes.ActivatedEventArgs s: Avalonia.Android.Platform.AndroidActivatableLifetime
```
i.e. only one event and no protocol args.

**Comment by amasidlovermedoc** [comment]
OK - it does appear that the event is indeed firing and working - however, there are two things to be aware of when testing... (Particularly noteworthy if using adb to send the intent)

1) If you use the same uri then the event args are only ProtocolActivatedEventArgs on the first use of the uri (until the app reloads).
2) If the app is already in the foreground and the uri hasn't changed then the event doesn't fire at all.

I'm still not quite there as my app crashes when I send a second URI to an already running instance - but that's either not Avalonia or a separate issue.
