### ISSUE TITLE
[IME Compatibility] Text is duplicated when committing with Shift key in WeChat Input (微信输入法)

### ISSUE THREAD

**Issue by laiwang233** [AvaloniaUI/Avalonia#19507]
### Describe the bug

When using the WeChat Input IME (微信输入法) in its Chinese mode, committing text to a TextBox by pressing the Shift key causes the text to be inserted twice.

For example, typing "hello" and then pressing Shift results in "hellohello" appearing in the TextBox.

This issue is specific to the WeChat Input IME. The bug does not occur when using the standard Microsoft Pinyin IME, which behaves correctly under the same conditions.

### To Reproduce

1. Set the system IME to WeChat Input.
2. Switch the IME to its Chinese mode.
3. Focus a TextBox in an Avalonia 11.3.4 application.
4. Type an English word, e.g., "test".
5. Press the Shift key.
6. Expected Result: The TextBox contains "test".
7. Actual Result: The TextBox contains "testtest".

### Expected behavior

When typing an English string (e.g., "hello") in the WeChat Input IME's Chinese mode, pressing the Shift key should commit the text to the TextBox only once.

The expected result should be "hello", not "hellohello".

### Avalonia version

Avalonia Version: 11.3.3

### OS

Windows

### Additional context

[JTest.zip](https://github.com/user-attachments/files/21928405/JTest.zip)
I have attached a minimal project that reproduces the bug. The project contains a single window with a standard TextBox.

![Image](https://github.com/user-attachments/assets/5c8401d1-90e5-48e0-b95c-615391c9e740)

**Comment by lextm** [comment]
"The bug does not occur when using the standard Microsoft Pinyin IME", then this is more likely to be a bug of WeChat IME than Avalonia.

**Comment by laiwang233** [comment]
> "The bug does not occur when using the standard Microsoft Pinyin IME", then this is more likely to be a bug of WeChat IME than Avalonia.

I understand this is a compatibility issue with third-party IMEs. Are there any plans to fix this?

**Comment by rabbitism** [comment]
> > "The bug does not occur when using the standard Microsoft Pinyin IME", then this is more likely to be a bug of WeChat IME than Avalonia.
> 
> I understand this is a compatibility issue with third-party IMEs. Are there any plans to fix this?

Maybe Tencent should fix it.

**Comment by laiwang233** [comment]
> > > "The bug does not occur when using the standard Microsoft Pinyin IME", then this is more likely to be a bug of WeChat IME than Avalonia.
> > 
> > 
> > I understand this is a compatibility issue with third-party IMEs. Are there any plans to fix this?
> 
> Maybe Tencent should fix it.

Thank you for the clarification and the detailed explanation.

I understand your position that this is a specific issue with the WeChat Input IME rather than a bug in Avalonia, especially since the standard Microsoft IME works correctly.

I will proceed by reporting this issue to the developers of WeChat Input. Accordingly, I am closing this issue now.

Thanks again for your time and support.

**Comment by yijie0110** [comment]
I'd like to request that this issue be reopened.

I have retested this issue with the latest Avalonia version, and the problem still exists.

Some additional information after further testing:

1. The issue is still reproducible with the latest Avalonia version.
2. The same version of WeChat Input works correctly in WPF, WinUI, WinForms, and other Windows applications. The duplicated text behavior only occurs in Avalonia applications.
3. The issue was previously considered likely to be a WeChat Input compatibility problem, and it was reported to the WeChat Input team. However, the latest WeChat Input version I tested, **2.1.2 (2026-07-23)**, still has the same behavior with Avalonia.
4. Since the same IME works normally with other Windows UI frameworks, I believe this should be treated as an Avalonia IME compatibility issue rather than solely as a bug in WeChat Input.

From an application developer's perspective, we cannot control which IME end users choose to install. If a widely used IME behaves correctly in WPF/WinUI/WinForms but causes duplicated input specifically in Avalonia, applications built with Avalonia are effectively affected by this compatibility issue.

Could you please reopen this issue and investigate whether Avalonia's Windows IME/TextInput handling can be made compatible with this behavior?

**Comment by fcxxxz** [comment]
rime输入法也会，看来是比较严重的问题了，一个一个的去让输入法厂商兼容，不如我们框架自己兼容，作者觉得呢
