### ISSUE TITLE
Wrong data in Avalonia DevTools

### ISSUE THREAD

**Issue by ds1709** [AvaloniaUI/Avalonia#20114]
### Describe the bug

Avalonia DevTools shows wrong data, that does't match actual values.

### To Reproduce

```xaml

  <Window.Styles>
    <Style Selector="ListBoxItem">
      <Setter Property="Padding" Value="5" />
    </Style>
  </Window.Styles>

  <ListBox>

    <ListBox.ItemContainerTheme>
      <ControlTheme TargetType="{x:Type ListBoxItem}" BasedOn="{StaticResource {x:Type ListBoxItem}}">
        <Setter Property="Padding" Value="0" />
      </ControlTheme>
    </ListBox.ItemContainerTheme>

    <Border BorderThickness="1" BorderBrush="Black">
      <TextBlock Text="A" />
    </Border>
    <Border BorderThickness="1" BorderBrush="Black">
      <TextBlock Text="B" />
    </Border>
    <Border BorderThickness="1" BorderBrush="Black">
      <TextBlock Text="C" />
    </Border>

  </ListBox>
```

<img width="1104" height="891" alt="Image" src="https://github.com/user-attachments/assets/2c55617d-61b6-47e3-85da-1c6238f0f313" />

* `Border`s inside ListBox shown as logical children of `Window`.
* Actual `Padding` of `ListBoxItem` is `5,5,5,5`, but in bottom right panel it shows `12,9,12,12`, and values `5,5,5,5` and `0,0,0,0` as overriden (crossed out).

### Avalonia version

11.3.8

**Comment by maxkatz6** [comment]
Issue with setters/frames was already fixed in the new DevTools.

> Borders inside ListBox shown as logical children of Window.

I am not sure if I follow. From the screenshots these are shown as logical children of ListBox.

**Comment by ds1709** [comment]
> From the screenshots these are shown as logical children of ListBox.

Sorry, my bad. Because of the duplication of borders inside `ListBox` and `ListBoxItem`s it seemed to me that they are inside window.

> Issue with setters/frames was already fixed in the new DevTools.

Where can I find this version of DevTool? The issue still persists in the latest version 11.3.9.

**Comment by maxkatz6** [comment]
@ds1709 check out https://docs.avaloniaui.net/accelerate/tools/dev-tools/getting-started

It has free community tier, that matches functionality of old devtools. There is more with full accelerate license.
