### ISSUE TITLE
Tooltip preventing view from being GCed

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2822]
Using ReactiveUI v0.8.1 on WIndows, when I navigate from view A to view B which contains a Button containing a Tooltip and open the tooltip and then navigate back to the previous view A, the view B is not GCed as the tooltip PopupRoot is holding the view in memory.
If I don't activate the tooltip, ViewB is GCed.

Here is the repo:
[App7.zip](https://github.com/AvaloniaUI/Avalonia/files/3482813/App7.zip)

In ViewModelB I allocate a 256K byte[].
Here is a memory dump after navigating to ViewB five times showing the non GCed ViewB and ViewModelB:

![image](https://user-images.githubusercontent.com/17591364/62721466-2b43a600-ba04-11e9-8b80-4c00fdf493d1.png)

**Comment by kekekeks** [comment]
Should be already fixed by https://github.com/AvaloniaUI/Avalonia/pull/2778

**Comment by aguahombre** [comment]
I updated the repo with latest NuGet pre-release Avalonia 0.8.999-cibuild0003269-beta and I am still getting the same memory leak.
[App7.zip](https://github.com/AvaloniaUI/Avalonia/files/3485478/App7.zip)

Do the latest NuGet builds contain the fix?

**Comment by kekekeks** [comment]
It seems that myget was refusing uploads again. Check 0.8.999-cibuild0003524-beta

**Comment by aguahombre** [comment]
Same problem
![image](https://user-images.githubusercontent.com/17591364/62853043-12c4db80-bce3-11e9-80a9-97cc3b120e05.png)

**Comment by aguahombre** [comment]
It appears that Tooltip.Close does not Dispose the popup therefore it leaks memory
```
        public void Close()
        {
            if (_popup != null)
            {
                _popup.SetChild(null);
                ((ISetLogicalParent)_popup).SetParent(null); // MISSING
                _popup.Hide();
                _popup.Dispose();  // MISSING
                _popup = null;
                DataContext = null;
            }
        }
```
