### ISSUE TITLE
Manjaro Linux dialogs doesn't work

### ISSUE THREAD

**Issue by HencoDesu** [AvaloniaUI/Avalonia#3248]
When I try to show OpenFileDialog apps crashes without any exception they are just closing. Before it parent window becomes darker, like everything is ok.
It's also crash in other app that works fine in another systems.
Code example: 
```cs 
public void OpenAvatar() {
    var dialog = new OpenFileDialog();
    dialog.Filters.Add(new FileDialogFilter { Name = "Изображения", Extensions = { "png", "jpg" } });
    var files = dialog.ShowAsync(Window).Result;
}
```
System: 
![изображение](https://user-images.githubusercontent.com/17922521/68627156-22281080-04ee-11ea-8986-09af8530d2f7.png)

**Comment by kekekeks** [comment]
It's a known issue with GTK dialogs, you can add `UseManagedFileDialogs` to your appbuilder as a workaround.

**Comment by Gillibald** [comment]
This should be fixed with the current preview of SkiaSharp. Only Skia symbols are now exported.

**Comment by t00** [comment]
This issue still exists in Avalonia 0.9.12. StartGtk crashes on the up to date Manjaro rolling distro.
Also, FileOpen and FileSave dialogs crash when UseManagedFileDialogs is used when Title is not set.

**Comment by kekekeks** [comment]
0.9.12 uses the old build of Skia.
