### ISSUE TITLE
TreeView.SelectedItem is set to null before being set to the newly selected item.

### ISSUE THREAD

**Issue by timothyparez** [AvaloniaUI/Avalonia#3576]
When selecting different items in a `TreeView` the value for the `SelectedItem` property  
is briefly set to `null` before being set to the newly selected item.  
 
Consider the following ViewModel:

```
public class MainWindowViewModel : ViewModelBase
{
    public ObservableCollection<string> Items {get; set;} = new ObservableCollection<string>();
            
    [Reactive]
    public string SelectedItem {get; set;}
    public MainWindowViewModel()
    {
        for (int i = 0; i < 10; i++)
        {
            Items.Add($"Item {i:##}");                
        }
        
        this.WhenAnyValue(x => x.SelectedItem)
            .Subscribe(x => Console.WriteLine($"Changed: {x ?? "null"}"));
    }      
}
```
As you select different items in the `TreeView` the console will output:

```
Changed: Item 6
Changed: null
Changed: Item 4
Changed: null
Changed: Item 6
Changed: null
Changed: Item 4
Changed: null
Changed: Item 6
Changed: null
Changed: Item 3
Changed: null
Changed: Item 7
```
This behavior differs from WPF and UWP.

[Sample repository](https://github.com/timothyparez/avaloniaui-treeview-selecteditem-issue)

**Comment by Kryptos-FR** [comment]
It is even worst than that, SelectedItem get sets to null and back to the original value when selecting the currently selected item. Breaks all my logic.

**Comment by grokys** [comment]
Yeah, if you could test/review https://github.com/AvaloniaUI/Avalonia/pull/3583 we can try and get that merged.

**Comment by Kryptos-FR** [comment]
@grokys Unfortunately I am unable to run Avalonia from the branch `refactor/use-selectionmodel`. I keep getting a BadImageException because of HarfBuzzSharp. I did a fresh clone and checked out that branch. Compiled fine but execution fails.

When Avalonia is configured with `UseSkia(`), the exception occurs in `Avalonia.Skia.FontManagerImpl` (line 16).
When Avalonia is configured with `UseDirect2D1()` the exception occurs in `Avalonia.Direct2D1.Media.GlyphTypefaceImpl` (line 22).

**Comment by grokys** [comment]
I've just updated that branch to latest master, hopefully this should fix it.

**Comment by Kryptos-FR** [comment]
Still not working. Looking more into the output folder, the wrong native *libHarfBuzzSharp.dll* gets copied, i.e. the *x86* version (766 KB) instead of the *x64* version (889 KB).

**Comment by grokys** [comment]
@Gillibald ☝️ have you seen this before?

**Comment by Gillibald** [comment]
I think that's a bug with the tooling. With AnyCPU it somehow fails to use the right native assets. Will try to figure out what is happening.

**Comment by Gillibald** [comment]
But I guess this is expected. To be safe just build against a specific platform. This would only work if you ship both native bins and select the right one at runtime.

**Comment by Kryptos-FR** [comment]
@Gillibald that seems to work for now if I specify explicitly the target.

@grokys I played a bit with the TreeView sample and it didn't work as expected, especially when deleting the selection. At that point I don't know if the issue is with the `SelectionModel` or with the code in `TreeViewPage.PageViewModel` but basically after multi-selecting all nodes from 1 to 9 and clicking on "Remove" only odd-indexed nodes were properly removed.

(sorry uploading images seems to be blocked at my work office)

**Comment by Kryptos-FR** [comment]
Bug described above is still there. And If I select from 1 to 9 while pressing SHIFT the catalog sample crashes (`NullReferenceException`).

**Comment by chenjing1294** [comment]
> iginal value w

version: 0.10.18, This issue doesn't seem to be resolved.

Problem recurrence: https://github.com/chenjing1294/avalonia_test
