### ISSUE TITLE
AvaloniaUI - XAML - Unable to resolve type from namespace

### ISSUE THREAD

**Issue by SCLD-JBuczkowski** [AvaloniaUI/Avalonia#3592]
Hi:

I believe I might have asked this previously, but I can't seem to find the post or reply, so I'll repost.

I've been working with the DevExpress MVVM assembly (.Net Core).
I created a version of the assembly that uses AvaloniaUI in place of WPF.

I'm including this assembly i my client project and am having difficulty with name space resolution in a XAML definition. I' using the above mentioned MVVM assembly (using AvaloniaUI) in place of the default version.

Consider the following XAML definition:
```
<Window  x:Class="Sample.Views.MainWindowView"
        xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:dxmvvm="http://schemas.devexpress.com/winfx/2008/xaml/mvvm"
        xmlns:views="clr-namespace:Sample.Views"
        xmlns:productionViewModels="clr-namespace:Sample.ViewModels.Production"
        xmlns:designViewModels="clr-namespace:Sample.ViewModels.Designer"
        WindowStartupLocation="CenterScreen"
        mc:Ignorable="d"
        Title="Sample" Height="720" Width="1280"
        DataContext="{dxmvvm:ViewModelSource Type=productionViewModels:MainWindowViewModel}"
        d:DataContext="{dxmvvm:ViewModelSource Type=designViewModels:MainWindowViewModel}">
```

**I get the following error:**
> Error	XAMLIL	Unable to resolve type ViewModelSource from namespace http://schemas.devexpress.com/winfx/2008/xaml/mvvm (line 13 position 9) Line 13, position 9.

I recall reading somewhere that I should try using the referenced assembly rather than the URL in the namespace definition. I'm unsure on how to do this.

Can someone help shed some light on this and what steps for resolution would be?

Thanks
JohnB

**Comment by kekekeks** [comment]
Are you sure that you have added corresponding XmlnsDefinitition attributes from Avalonia? They are used to match xmlns aliases with actual .NET namespaces. Alternatively you could use `clr-namespace` declarations.

**Comment by SCLD-JBuczkowski** [comment]
In the definiiton, I'm including
xmlns="https://github.com/avaloniaui"

Is there something additionally that  should be using?
I'm sorry. I'm not sure I follow.
Can you please give more details?
Would a small sample project help?

Thanks

**Comment by helmesjo** [comment]
Any update on this? I'm seeing the same problem, which (occasionally) causes the preview to fail to load.

**Comment by camelCaseCo** [comment]
I was wondering the same thing as @helmesjo, will there be any problems if `assembly=assembly_name` is removed?

**Comment by kekekeks** [comment]
>any problems if assembly=assembly_name is removed?

It shouldn't as long as view model classes are in the same project.

**Comment by JanRomero** [comment]
@camelCaseCo @helmesjo Replacing the underscore with a space did it for me. No need to remove the assembly entirely. Probably best to just not put spaces in the project name in the first place&hellip;

**Comment by Tenjim** [comment]
Hi,

There is any update of this ticket? Because I have a similar issue when I want to use an other project reference with this kind of namespace :

Same example of @helmesjo
`xmlns:vm="clr-namespace:some.namespace.ViewModels;assembly=my_assembly"`

I had already try to remove assembly code like suggested above.

**Comment by ReferenceType** [comment]
I have same issue each time I make a new user control. My workaround is to instantiate the view model somewhere in its assembly then rebuild the assembly. Otherwise type is never resolved.

**Comment by timunie** [comment]
> I have same issue each time I make a new user control. My workaround is to instantiate the view model somewhere in its assembly then rebuild the assembly. Otherwise type is never resolved.

Any chance to upload a minimum sample and some screenshots?

**Comment by TrinterSoftware** [comment]
[DatagridTester.zip](https://github.com/AvaloniaUI/Avalonia/files/14043717/DatagridTester.zip)

I've here a litte project using .net 8. dotnet run works but with dotnet publish I get 
these errors:
![image](https://github.com/AvaloniaUI/Avalonia/assets/150950968/b3318c9e-5726-440b-9622-674f4373dc61)

**Comment by maxkatz6** [comment]
I am going to close this issue. If somebody can reproduce the exact same issue with repro - please let me know.

**Comment by TrinterSoftware** [comment]
Thank you for having a look. Next time I'll better check before posting.

**Comment by tiborkerenyi** [comment]
> I am going to close this issue. If somebody can reproduce the exact same issue with repro - please let me know.

Hi,

I have a same issue. My steps for repro in VS (.Net 8):

1. Create usercontrol in a dedicated folder
2. Start the project, of course viewmodel and all necessary classes should work
3. Create a new usercontrol in the dedicated folder
4. The AXN001 and AXN002 error messages will be displayed when building

Hope this helps you.

**Comment by TrinterSoftware** [comment]
[DatagridTester.zip](https://github.com/AvaloniaUI/Avalonia/files/14076503/DatagridTester.zip)

Here is a little Testproject. The error only occours when:

- build with .net 8.0 
- self-contained deployment
- target-runtime win-x86
- click on the grid rows multiple times or move the mouse above the grid header then the program crashes with one of these Stacktraces:

---
Object reference not set to an instance of an object.
   at Avalonia.Controls.Primitives.DataGridColumnHeadersPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass()
   at Avalonia.Controls.Window.ShowCore(Window owner)
   at Avalonia.Controls.Window.Show()
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.ShowMainWindow()
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at DatagridTester.Program.Main(String[] args) in E:\Projekte\DatagridTester\Program.cs:line 22


---
Object reference not set to an instance of an object.
   at Avalonia.Controls.DataGridColumnHeader.SetDragCursor(Point mousePosition)
   at Avalonia.Controls.DataGridColumnHeader.DataGridColumnHeader_PointerMoved(Object sender, PointerEventArgs e)
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|4_0[TEventArgs](Delegate baseHandler, Object sender, RoutedEventArgs args)
   at Avalonia.Interactivity.Interactive.<>c__4`1.<AddHandler>b__4_1(Delegate baseHandler, Object sender, RoutedEventArgs args)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseMove(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties properties, KeyModifiers inputModifiers, Lazy`1 intermediatePoints, IInputElement hitTest)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at DatagridTester.Program.Main(String[] args) in E:\Projekte\DatagridTester\Program.cs:line 22

---

Maybe the x86-target is not so important. One can go back to .net 6 or 7 or deploy the old way with a runtime required.

**Comment by timunie** [comment]
Do you have trimming enabled? If so, this is likely the reason. DataGrid has problems with AOT / Trimming.

**Comment by TrinterSoftware** [comment]
No trimming was disabled.

**Comment by librashuai** [comment]
according to this document https://docs.avaloniaui.net/docs/basics/data/data-binding/compiled-bindings
i change to 
xmlns:vm="using:MyApp.ViewModels"
then problem is resolved.

**Comment by tiborkerenyi** [comment]
> according to this document https://docs.avaloniaui.net/docs/basics/data/data-binding/compiled-bindings i change to xmlns:vm="using:MyApp.ViewModels" then problem is resolved.

I tried this, it works only in the first uc. In the second uc it doesn't solve the issue, but the first one works correctly.

**Comment by maxkatz6** [comment]
@tiborkerenyi is it a previewer project? If so, do you rebuild your project between steps 3 and 4? If it's a compile error, can you upload a zip with small project?

**Comment by tiborkerenyi** [comment]
> @tiborkerenyi is it a previewer project? If so, do you rebuild your project between steps 3 and 4? If it's a compile error, can you upload a zip with small project?

[AvaloniaUCIssue.zip](https://github.com/AvaloniaUI/Avalonia/files/14136974/AvaloniaUCIssue.zip)

@maxkatz6  I created a new project to repro the issue. The error message is about the namespace of UserControl1/UserControl2.
This is still .Net7, I haven't upgraded to .Net8 until it works this way.
Please examine what am I doing wrong. Thank in advance.

**Comment by maxkatz6** [comment]
@tiborkerenyi your user controls have AvaloniaUCIssue namespace
![image](https://github.com/AvaloniaUI/Avalonia/assets/3163374/167637ce-fcd0-4c14-a4e6-3e2302a1f374)

So, replace `xmlns:uc="using:AvaloniaUCIssue.Usercontrols"` with `xmlns:uc="using:AvaloniaUCIssue"`

**Comment by tiborkerenyi** [comment]
Oh, thanks a lot. 🙂
