### ISSUE TITLE
Arabic doesn't render correctly

### ISSUE THREAD

**Issue by ahmed-abdelrazek** [AvaloniaUI/Avalonia#3777]
Arabic and i guess other RTL languages doesn't render correctly 
the words are backward and the characters are separated
also custom fonts doesn't render it at all 

![Annotation 2020-04-13 000351](https://user-images.githubusercontent.com/7858946/79081096-8c9de080-7d1a-11ea-84a6-e2e4a09e7e6b.png)

i wrote مرحبا 
م ر ح ب ا
i got
ا ب ح ر م

this windows 10 x64 pro 1909 
![image](https://user-images.githubusercontent.com/7858946/79081117-af2ff980-7d1a-11ea-844a-b52b191e6455.png)

**Comment by Gillibald** [comment]
Is TextBlock rendering everything correctly? TextBox currently only has very basic rendering capabilities.

**Comment by ahmedflix25** [comment]
yes, TextBlocks work as expected even with custom fonts

![image](https://user-images.githubusercontent.com/7858946/79081754-83b00d80-7d20-11ea-884a-c9717ddec4c3.png)

**Comment by Gillibald** [comment]
Okay good. Thanks for testing

**Comment by roceh** [comment]
I know this might seem a small issue, but after all your recent progress (fluent theme & performance improvements) the lack of good multi lingual support for CJK/Arabic/Thai and other languages with odd diacritics is perhaps the last thing stopping me using avalonia for a revamp of a commerical app (currently winforms).  As it is I will unforunately have to go with WPF.

Have you considered at aleast trying to integrate the native text box (borderless) into the text box renderer (e.g. only when it has focus). I just anticipate there are probably dozens of edge cases for different locales that are not easy to discover if you roll your own text box.

**Comment by jmacato** [comment]
@roceh No, I'm afraid that solution wont work with us. It doesn't seem to be a clean and cross platform way of providing input. But don't fret since we're still actively working on fixing our TextBox implementation to fully support Unicode.. Hopefully by that time we fix it, you could re-consider using Avalonia in your projects :)

**Comment by roceh** [comment]
I just noticed 0.10 got released, is the new NativeControlHost (Native embedding) basically what I was suggesting. i.e. could it be used to wrap the windows text box, style it and use it as a control until you have your textbox implementation fully complete? How does it behave with regard tab focus, if i host a system focusable control does it play nice with avalonias focus system? i.e. can I tab off it to a standard avalonia control for example.

**Comment by Takoooooo** [comment]
Fixed in #4893.

**Comment by lilmahyar** [comment]
Arabic characters still doesn't render correctly when typing in textbox .

**Comment by timunie** [comment]
@lilmahyar which Avalonia version are you using? If 0.10.x, please try out 11.0 rc1 if 11.0 RC1 doesn't solve your issue, please open a new issue with detailed steps to reprodue, esp. The entered text and the expected outcome. 

Note: in general it's not wise to answer closed issues. There's a high chance that we miss new comments here as closed issues are not revisited. Thx 🙏
