### ISSUE TITLE
Problems on DataGrid

### ISSUE THREAD

**Issue by fredericoregateiro** [AvaloniaUI/Avalonia#3806]
With the dark theme the selected row values cannot be read.
The String format doesn't work properly:
```xml
<DataGridTextColumn Header="Incidência" Binding="{Binding AffectedValue, StringFormat=\{0:N2\}}"/>
<DataGridTextColumn Header="IVA" Binding="{Binding VATValue, StringFormat=\{0:N2\}}"/>
<DataGridTextColumn Header="Desconto" Binding="{Binding Discount, StringFormat=\{0:N2\}}"/>
<DataGridTextColumn Header="Total" Binding="{Binding Total, StringFormat=\{0:C\}}" />
```
The last column should display 2 decimal places and the currency simbol, and the 3 columns before should have 2 decimal places.

How can i align the values to the right?

![avalonia](https://user-images.githubusercontent.com/6304701/79917908-56034c80-8423-11ea-86c7-56c3bebf2327.png)

**Comment by Symbai** [comment]
> 
> 
> With the dark theme the selected row values cannot be read.

Upgrade to latest (preview) version. This is fixed already https://github.com/AvaloniaUI/Avalonia/pull/3564

**Comment by fredericoregateiro** [comment]
I was using the 0.9.8 and updated to version 0.9.9 today, the problem remains on the datagrid theme.
I'm using these styles:
```xml
<StyleInclude Source="avares://Avalonia.Themes.Default/DefaultTheme.xaml"/>
<StyleInclude Source="avares://Avalonia.Themes.Default/Accents/BaseDark.xaml"/>
<StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Default.xaml"/>
```

**Comment by Gillibald** [comment]
This is fixed in the current master and not in the release. Use a recent nightly build if you want to use this fix.
