### ISSUE TITLE
Width and Height are ignored if ExtendClientAreaToDecorationsHint is set to True.

### ISSUE THREAD

**Issue by FrankenApps** [AvaloniaUI/Avalonia#4248]
I am using Avalonia 0.10.0-preview1.

Width and Height are ignored in that case:
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="clr-namespace:MyApp.ViewModels;assembly=MyApp"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d"
        Width="300"
        Height="400"
        x:Class="MyApp.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="MyTitle"
        ExtendClientAreaToDecorationsHint="True"
        TransparencyLevelHint="None"
        WindowStartupLocation="CenterScreen">
```

**Comment by FrankenApps** [comment]
Also if I set `TransparencyLevelHint="Transparent"` nothing happens for me on windows.

**Comment by FrankenApps** [comment]
This would be a workaround for my first Issue:
```
        public MainWindow()
        {
            InitializeComponent();

            Width = 300;
            Height = 400;
        }
```

**Comment by danwalmsley** [comment]
> Also if I set `TransparencyLevelHint="Transparent"` nothing happens for me on windows.

What OS are you on? TransparentLevelHint is just a hint so some OS dont support transparency...

However your Window background usually covers the transparent area.. so you need to set `<Window Background="{x:Null}"` or `<Window Background="Transparent"`

**Comment by FrankenApps** [comment]
I am on Windows 10. Yes, setting the Window Background to transparent worked. Maybe this should also be made clear in the ControlCatalog, because the Theme seems to override the windows background color, so that transparency has no Effect on the "Window Customizations" Page.

**Comment by FrankenApps** [comment]
I think there is another related problem (to the Width and Height) Issue, too. It can be also seen in the ControlCatalog: When ExtendClientArea and PreferSystemChrome are activated, it is impossible to drag the Window on Windows10.

**Comment by danwalmsley** [comment]
seems to be fixed...

@FrankenApps will close but re-open if issues persist. Will release a 0.10.0-preview2 shortly with any recent fixes in it.

**Comment by FrankenApps** [comment]
Yes, it is fixed. There is one more tiny thing, but I honestly don't care that much about it.

If ExtendClientArea is true and PreferSystemChrome is false, then it is still possible to click the title bar and close the window, even though no button is visible. It is also impossible to drag the window in the area where the window controls would normally be located.

Just wanted to let you know about this, but closing that particular issue because it is resolved.

**Comment by danwalmsley** [comment]
@FrankenApps https://github.com/AvaloniaUI/Avalonia/pull/4336/files will fix the dragging thing...

you must also uncheck Titlebar to prevent that closing behavior you report on windows i beleive.

**Comment by Resonanz** [comment]
This is still an issue on 11.02 (latest, September 2023). How is this "production ready"?
