### ISSUE TITLE
TextBlock wrapping causes text alignment Center to be off center  

### ISSUE THREAD

**Issue by sasa-tomicic** [AvaloniaUI/Avalonia#4830]
Repro:
`<TextBlock Text="STRIKE TAKEN" TextAlignment="Center" TextWrapping="Wrap" />`

Looks like in 0.10 wrapping causes width to be calculated based on "STRIKE_" instead on "STRIKE", which puts string a bit off center to the left with TextAlignment="Center" + TextWrapping="Wrap".

Picture displays output for same control in WPF, Avalonia 0.9 and 0.10.

![Avalonia wrap issue](https://user-images.githubusercontent.com/37650659/95583692-cbe48a00-0a3c-11eb-83d4-e2793f4b2dff.png)

**Comment by donandren** [comment]
also alight to right doesn't align perfect texts with wrap:
example:
```xaml
    <StackPanel Margin="5" HorizontalAlignment="Left">
      <Border BorderBrush="Black" BorderThickness="1" >
        <TextBlock FontSize="30" Text="Wrapped Wrapped Wrapped Wrapped" TextAlignment="Right" TextWrapping="Wrap" Width="150" />
      </Border>
    </StackPanel>
```
result:
![image](https://user-images.githubusercontent.com/13854631/95893035-12651c00-0d90-11eb-9cdb-ceffa05eb12a.png)
wpf expected:
![image](https://user-images.githubusercontent.com/13854631/95893148-33c60800-0d90-11eb-9484-2487a83b9219.png)

**Comment by Gillibald** [comment]
![Screenshot 2021-04-22 134054](https://user-images.githubusercontent.com/5928797/115708539-6f114700-a370-11eb-9337-a4469d78136b.png)

This is fixed in #5407

**Comment by Lev02** [comment]
Avalonia 11.3.9, issue is still there.

```
<TextBlock MaxWidth="40"
               TextWrapping="Wrap" TextAlignment="Right"
               VerticalAlignment="Top"
               HorizontalAlignment="Stretch"
               Foreground="Black" Background="White"
               Text="test test test test" />
```

<img width="41" height="68" alt="Image" src="https://github.com/user-attachments/assets/a7c74c8e-f9c9-4944-82e6-7fbc1ba3596e" />
