### ISSUE TITLE
Control Catalog gets Null Reference Exception on startup MacOS

### ISSUE THREAD

**Issue by mrj001** [AvaloniaUI/Avalonia#5028]
I built Avalonia from source, with HEAD at c682895b2.  This included updating my build of the native components.

Now in folder samples/ControlCatalog.NetCore, I run
`$ dotnet run`
and get the following Exception:

> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
>    at Avalonia.Native.WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.Resized(AvnSize* size) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Native/WindowImplBase.cs:line 179
>    at Avalonia.Native.Interop.Impl.__MicroComIAvnWindowBaseEventsVTable.Resized(IntPtr this, AvnSize* size) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Native/Interop.Generated.cs:line 2694
> --- End of stack trace from previous location where exception was thrown ---
>    at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Native/PlatformThreadingInterface.cs:line 59
>    at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
>    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
>    at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
>    at ControlCatalog.NetCore.Program.Main(String[] args) in /Users/mj/Documents/develop/avalonia/Avalonia/samples/ControlCatalog.NetCore/Program.cs:line 101
> 

Here is my output from dotnet --info:

> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.401
>  Commit:    39d17847db
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.15
>  OS Platform: Darwin
>  RID:         osx.10.15-x64
>  Base Path:   /usr/local/share/dotnet/sdk/3.1.401/
> 
> Host (useful for support):
>   Version: 5.0.0
>   Commit:  cf258a14b7
> 
> .NET SDKs installed:
>   3.1.201 [/usr/local/share/dotnet/sdk]
>   3.1.302 [/usr/local/share/dotnet/sdk]
>   3.1.401 [/usr/local/share/dotnet/sdk]
>   3.1.402 [/usr/local/share/dotnet/sdk]
>   3.1.403 [/usr/local/share/dotnet/sdk]
>   5.0.100 [/usr/local/share/dotnet/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET runtimes or SDKs:
>   https://aka.ms/dotnet-download
>

**Comment by donandren** [comment]
you need to use build script at least once to build the native dependencies first.
try:
`sh build.sh Compile` - to compile all projects
or alternatively
`sh build.sh CompileNative` - to compile only the native library dependencies

**Comment by mrj001** [comment]
I built the native components per the instructions [here](https://github.com/AvaloniaUI/Avalonia/blob/master/Documentation/build.md#build-native-libraries-macos-only).

To check if the script vs. Xcode application build it differently, I did this:
```
$ git clean -xdf
$ ./build.sh CompileNative
$ ./build.sh --target Package --skip-previewer --configuration Debug
$ cd samples/ControlCatalog.NetCore
$ dotnet run
```

I got the same exception - stack traces match.

**Comment by mrj001** [comment]
However, it is happening with the Avalonia template (`dotnet new Avalonia.app`).

I made two changes to that - it refers to a locally built nuget repo containing packages built from HEAD=3ab822247, and changed the versions in the project references to 0.10.999.

Here is an example project (with the nuget packages themselves removed to save 14MB):
[tmp.zip](https://github.com/AvaloniaUI/Avalonia/files/5562151/tmp.zip)

**Comment by ahopper** [comment]
I've just had a user report the same exception using 0.10.999-cibuild0011949-beta maybe related to #5067 ?

**Comment by danwalmsley** [comment]
fixed.

**Comment by mrj001** [comment]
@danwalmsley 
I'm still getting a Null Reference Exception with the Avalonia template:

> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
>    at Avalonia.Native.WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.Resized(AvnSize* size)
>    at Avalonia.Native.Interop.Impl.__MicroComIAvnWindowBaseEventsVTable.Resized(IntPtr this, AvnSize* size)
> --- End of stack trace from previous location where exception was thrown ---
>    at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken)
>    at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
>    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
>    at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
>    at Issue5028.Program.Main(String[] args) in /Users/mj/Documents/develop/avalonia.learn/Issue5028/Program.cs:line 13

My HEAD is now at 2e2f9f2bf

**Comment by mrj001** [comment]
@danwalmsley 
Found the problem.  There was an old build of libAvaloniaNative.dylib in a Nuget cache.  Fixed that, and it works now.
