### ISSUE TITLE
Exception when using Edit and Continue on Visual Studio 2019 for Windows

### ISSUE THREAD

**Issue by csulmone** [AvaloniaUI/Avalonia#5456]
**Describe the bug**
Exception when using Edit and Continue on Visual Studio 2019 for Windows

**To Reproduce**
1. Created a new Avalonia MVVM Application via the Visual Studio extension. (Avalonia 0.10)
2. Set a breakpoint anywhere
3. Debug the application
4. Breakpoint hit
5. Make any code modification
6. This error appears
Severity    Code    Description    Project    File    Line    Suppression State
Error    CS7038    Failed to emit module 'AvaloniaApplication1': Changing the version of an assembly reference is not allowed during debugging: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' changed version to '2.1.0.0'.    AvaloniaApplication1        1    Active

**Expected behavior**
Don't crash

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 0.10.0

**Comment by rstm-sf** [comment]
This also happens in Rider

**Comment by csulmone** [comment]
This only happens when modifying code at runtime in a module that references Avalonia. Other modules without a dependency on Avalonia can be edited at runtime and continued.

**Comment by workgroupengineering** [comment]
I suspect it may be due to compiling the Xaml not updating the debug information for some reason.

**Comment by marbel82** [comment]
@csulmone Are you using Fody.PropertyChanged in AvaloniaApplication1 or does Avalonia inject some code at compile time like Fody?

I have same CS7038 error, when I change code during debugging.

A few years ago I had a similar problem when Fody.PropertyChanged was added to the project, but then they fixed something and the problem disappeared.

**Comment by unominhtuan** [comment]
is there any fix for this? it makes me have to rebuild the project every time the code is fixed, and slows down the coding

**Comment by marbel82** [comment]
I found the cause in my case. In all projects I have set TargetFramework to `net5.0-windows`, but in one I had set `net.5.0`. When I changed in this latest project to `net5.0-windows`, the problem with inability to edit disappeared.

**Comment by RobertBeekman** [comment]
Unfortunately this issue still occurs with .NET 6 and Visual Studio 2022. Is there any attention to address this? Not being able to use Edit & Continue can be a major blow to productivity :(

**Comment by marbel82** [comment]
@RobertBeekman We also migrated to .NET6 and the problem returned. I have not found a solution for this. Maybe one of the NuGets is causing this problem.

**Comment by oli-g-sk** [comment]
Same here, a fresh install of VS 2022, projects re-targeted to .NET 6, and cannot try hot reload 😥

**Comment by marbel82** [comment]
I think this is the wrong issue to talk about the problem. Mayby we should "report a problem" in Visual Studio or write an issue at https://github.com/dotnet/runtime/issues.

**Comment by danipen** [comment]
Any plans to take a look into it guys? 

Edit and continue and hot reload are features that saves the developer a lot of time and they're not working in Avalonia...

**Comment by yll690** [comment]
Same problem. Any progress?

**Comment by turboluk** [comment]
Hi, I register same issue both in Visual Studio and Rider.

**Comment by sudongg** [comment]
Is there any progress? vs2022 .net5 and .net6 still cannot hot reload.
The hot reload function will greatly improve development efficiency.

**Comment by yingDev** [comment]
same with 11-preview4 + .net7

**Comment by danipen** [comment]
Are there any plans to add edit and continue / hot reload for .net 7?

**Comment by Jure-BB** [comment]
I encountered same issue when trying default Avalonia templates, but using templates from https://github.com/AvaloniaUI/Avalonia.Markup.Declarative hot reload works for me. 

Note that, this approach won't be suitable for everyone, as C# is used to define views markup instead of XAML. But from my initial tests, there seems to be even less friction using Markup.Declarative than using XAML, to define views. At least, that's been my experience.

**Comment by SimonCropp** [comment]
my guess would be that Avalonia.Build.Tasks is modifying the assembly after a compile, which woould prevent hot reload from patching it since the hash would be different. We have the same problem in Fody

**Comment by timunie** [comment]
Hi @SimonCropp , 

may be related, yes. Do you know if there is any way to fix it or a workaround an user can do? Would be really neat. 

Happy coding
Tim

**Comment by SimonCropp** [comment]
@timunie unfortunately, no i do not know of any workaround

**Comment by unofficialdev** [comment]
.

**Comment by maxkatz6** [comment]
Workaround is to target the same .NET target framework version as Avalonia does.
I.e., it's either .NET 6 (in 11.0) or .NET Standard 2.0. Then hot reload in c# code works fine.

**Comment by timunie** [comment]
👀 Can't believe that it now finally works (I had to try it directly ^^). This is a huge step for the debugging experience 👍 . Good job guys.

**Comment by maxkatz6** [comment]
@timunie I used edit and continue even before with Avalonia and it worked. It was a quite specific use case, when it didn't, see - https://github.com/AvaloniaUI/Avalonia/issues/5456#issuecomment-1547044071

But I guess it was a way bigger problem with 0.10, which is only netstandard.
