### ISSUE TITLE
 IndexOutOfRangeException: Could not recycle container: not materialized.

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#606]
IndexOutOfRangeException: Could not recycle container: not materialized.
Exception is thrown during application close from time to time.
at https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Generators/ItemContainerGenerator%601.cs#L91

   at Avalonia.Controls.Generators.ItemContainerGenerator`1.TryRecycle(Int32 oldIndex, Int32 newIndex, Object item, IMemberSelector selector) in Avalonia\src\Avalonia.Controls\Generators\ItemContainerGenerator`1.cs:line 94

**Comment by donandren** [comment]
Owner ListBox of the ItemContainerGenerator have:
	Avalonia.LogicalTree.ILogical.IsAttachedToLogicalTree	false	bool

**Comment by grokys** [comment]
Do you have a repro for this?

**Comment by danwalmsley** [comment]
I was getting this also, but went away with the fix you did to itemvirtualizer, @donandren do you agree this is fixed?

**Comment by donandren** [comment]
still don't have a stable repro, this is still happening very rare. I will continue the attempts to find a proper repro.
