### ISSUE TITLE
Menu with submenus won't open

### ISSUE THREAD

**Issue by braca** [AvaloniaUI/Avalonia#6827]
**Describe the bug**
I've updated from 0.10.7 to 0.10.10 and Menus seems to be broken (at least in macOS)

Whenever I press a Menu (that have sub-menu items), the menu won't stay open, it just flicks and automatically closes

**To Reproduce**

Create a sample project, and in the main view add a Menu with subitems
Then press the `Test` menu
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="using:menu_bug.ViewModels"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="menu_bug.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="menu_bug">

    <Design.DataContext>
        <vm:MainWindowViewModel/>
    </Design.DataContext>

    <StackPanel>
        <Menu>
            <MenuItem Header="Test">
                <MenuItem Header="Test 1"></MenuItem>
                <MenuItem Header="Test 2"></MenuItem>
            </MenuItem>
            
        </Menu>
        <TextBlock Text="{Binding Greeting}" HorizontalAlignment="Center" VerticalAlignment="Center"/>
    </StackPanel>
</Window>
```

**Expected behavior**
The menu should remain open until the user clicks on a menu item, or somewhere else

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS Monterey 12.0.1
- Version 0.10.10

**Additional context**

**Comment by HendrikMennen** [comment]
Yes I noticed that too. This bug only exists on MacOS. 0.10.8 works, 0.10.10 not

**Comment by maxkatz6** [comment]
Can't reproduce on windows. Don't have access to macos at the moment.
@danwalmsley

**Comment by HendrikMennen** [comment]
This is probably the most breaking bug with the current version afaik, as it makes MacOS apps with menus unusable.
Probably has something to do with #6803 or #6700

**Comment by sn4k3** [comment]
I have the same problem, but for me it dont require submenus, it will flicker and close a simple menu too.
But if i ALT + hotkey of the menu it will open, but i can't use mouse nor arrows to navigate it, but press enter does trigger the menu item

**Comment by maxkatz6** [comment]
It should be fixed with latest master. Can anybody confirm?

**Comment by mohdimas** [comment]
I just tried it on the latest master branch, and the issue is still there for me.

**Comment by grokys** [comment]
@danwalmsley after #6700 we seem to be getting non-client clicks reported immediately after opening the menu, which causes the menu to close.

**Comment by svenhue** [comment]
I am using version 11.0.0 preview5 on macOS and the menu only opens on click after entering full screen first. 
After that , it works as usual.

Is this behavior expected?

**Comment by davidzemancz** [comment]
I have the same problem as @svenhue. Will the issue be solved anytime soon? 

Using macOS 14.5 (23F79), Avalonia packages 11.1.0, .net 8.

**Comment by cainmartin** [comment]
Yeah, I am getting this in Avalonia 11.2.3, .net8 and MacOS 15.1
