### ISSUE TITLE
DllNotFoundException on Windows 11 and Visual Studio 2022 with .net core 6

### ISSUE THREAD

**Issue by karthitect** [AvaloniaUI/Avalonia#7505]
Hi

I'm using Windows 11 and created a new Avalonia app using

`> dotnet new avalonia.mvvm -o MyApp`

And when I start the app using Visual Studio 2022, I get the following error:

```
System.TypeInitializationException: 'The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.'
Inner Exception
DllNotFoundException: Unable to load DLL 'libSkiaSharp' or one of its dependencies: The specified module could not be found. (0x8007007E)
```

![image](https://user-images.githubusercontent.com/44182099/151978413-e0e02edd-051b-4554-a6c8-6a7a9e30ebc3.png)

Here's the project configuration:

![image](https://user-images.githubusercontent.com/44182099/151978563-74f81b1b-76cb-4c7c-8d87-1b2df3fed18f.png)

Any suggestions would be appreciated on how to get past this error. Thanks!

**Comment by CatWithAutism** [comment]
@karthitect i've solved this issue via 
`dotnet workload install wasm-tools`

When you install this you have to enable it in your .csproj file
```
<WasmNativeStrip>true</WasmNativeStrip>
<RunAOTCompilation>true</RunAOTCompilation>
```

Please give me a feedback if it helps you.

**Comment by CatWithAutism** [comment]
Actually I fixed my Web Solution in this way but I guess this problem is related to yours

**Comment by CatWithAutism** [comment]
> > @karthitect ![image](https://user-images.githubusercontent.com/28768640/165784693-bded1b7e-f77b-4362-9a28-5dbea7dec38d.png) or you mean a parent tag?
> 
> Yea, I meant the parent tag around this. Thanks

![image](https://user-images.githubusercontent.com/28768640/165791299-9f32a9c8-7f3e-48e1-9c3c-fa136add47e7.png)

**Comment by karthitect** [comment]
Thanks, I tried that. But still getting the original error :(

**Comment by schnerring** [comment]
> dotnet workload install wasm-tool

That's what it fixed for me. [It's also mentioned in the docs](https://docs.avaloniaui.net/tutorials/running-in-the-browser#troubleshooting).
