### ISSUE TITLE
Typing in hebrew gives seemingly wrong encoding

### ISSUE THREAD

**Issue by AsafMahlev** [AvaloniaUI/Avalonia#8704]
**Describe the bug**
When typing in Hebrew in a textbox, the letters come out not in hebrew "דוגמה", but as diacritic letters -  "ãåâîà"
When pasting hebrew text, it works fine.

**To Reproduce**
      `  <TextBox ></TextBox>`
Type in hebrew.

**Expected behavior**
Typing in hebrew will produce hebrew text

**Screenshots**
<img width="249" alt="image" src="https://user-images.githubusercontent.com/109351094/183484722-f88c1d2c-fa58-41ea-a99d-592b26315789.png">

when pasting:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/109351094/183484767-8f2670c1-6937-4e62-b5a6-1743e47fee3b.png">

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)] Windows 11
- Version [e.g. 0.10.0-rc1 or 0.9.12] Tried on both 0.10.17 and the latest nightly

**Additional context**

**Comment by Gillibald** [comment]
Supported by current master. Won't be fixed in 0.10.x

**Comment by AsafMahlev** [comment]
I'm on the newest nightly (0.10.999-cibuild0022654-beta) and it is still happening.
Is it not updated with the master?

**Comment by Gillibald** [comment]
I am specifically testing Hebrew as a writing system and did not have any issues typing. Do you actually set your current locale to Hebrew?

**Comment by AsafMahlev** [comment]
Do I need to specify a locale in Avalonia?

My computer's language is English, but I'm using all the hebrew culture settings - 
<img width="652" alt="image" src="https://user-images.githubusercontent.com/109351094/183507336-7253842c-59ca-4076-99a8-5f7255060a65.png">

**Comment by Gillibald** [comment]
To get an better idea how you type please let me know your actual key presses so I can investigate why some sequences are not shaped correctly.

I know that typing Hebrew requires changes key layouts on different level but I don't know how to form proper sequences.

**Comment by Gillibald** [comment]
The keyboard layout needs to  be changed to Hebrew otherwise keys are not mapped correctly and you don't get all pages required to type.

**Comment by Gillibald** [comment]
https://support.content.office.net/en-us/media/4f8c6bb8-f5a6-315a-dd19-64bd374d654f.png

**Comment by Gillibald** [comment]
If this usually works for you without changing the keyboard layout we need to find out how other editors handle this.

**Comment by AsafMahlev** [comment]
<img width="97" alt="image" src="https://user-images.githubusercontent.com/109351094/183509363-5c7906d5-8a6f-4cf4-87c1-225275fd41bf.png">
My keyboard layout is hebrew when I type in hebrew (I switch layouts between hebrew and english with shift+space).
Any other program/textbox works fine, but here instead of hebrew, when my layout is hebrew it writes these weird diacritic instead.



This is the output of the KeyUp Event (When I try to type in hebrew):
<img width="338" alt="image" src="https://user-images.githubusercontent.com/109351094/183509475-6fd97582-a6a2-41e7-935c-9cf63dfca5dc.png">

**Comment by Gillibald** [comment]
Will investigate myself in a few hours. Thanks for your detailed information.

We track text processing bugs here: https://github.com/AvaloniaUI/Avalonia/issues/8070

Feedback is highly appreciated.

Let's keep this specific issue open.

**Comment by Gillibald** [comment]
Can't repro:

https://user-images.githubusercontent.com/5928797/192689633-0f35f8fd-9e06-41ec-9e75-2149f7596bb6.mp4
