### ISSUE TITLE
MenuItems on Simple Theme on 125% DPI has scrolling arrows

### ISSUE THREAD

**Issue by nesrak1** [AvaloniaUI/Avalonia#9501]
**Describe the bug**
When Windows DPI is set to 125% on programs using the Simple theme, the scrolling arrow shows up on all menu item groups no matter the size. This bug does not occur on 100% or 150% DPI and does not occur when using Fluent theme.

**To Reproduce**

1. Be on Windows with 125% DPI
2. Create an app with Simple theme with a Menu
3. Open the menu
4. See the scrolling arrow

**Expected behavior**
The arrow should not appear unless the menu is too big.

**Screenshots**

On 125% DPI:
![OofAvalonia_v3dlBokM4w](https://user-images.githubusercontent.com/12544505/203083268-f87c24d5-ad4b-41d2-aa6e-81083009174d.png)

On 150% DPI:
![OofAvalonia_uiTIA0BaUo](https://user-images.githubusercontent.com/12544505/203083324-6386e22e-578d-4073-99cf-6ce846a78b66.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.0-preview4 (did not occur in 0.10)

**Comment by timunie** [comment]
@nesrak1 thank you for finding this. 

@AvaloniaUI/core I added this to the 11.0 board as I think it should be solved if it was not an issue before. If you disagree, remove it.

**Comment by nesrak1** [comment]
Yep, turns out this is a general ScrollViewer issue and not a Menu issue. Here's a regular ScrollViewer I have that has no overflow still showing a scrollbar:

100% DPI
![UABEAvalonia_7ZjycrOir5](https://github.com/AvaloniaUI/Avalonia/assets/12544505/bb8a5295-d3b2-4f58-bb0d-c4e55a507457)

125% DPI
![UABEAvalonia_RyVGbwKrpw](https://github.com/AvaloniaUI/Avalonia/assets/12544505/355944d7-1566-45db-8b48-896cbf67a65a)

I'm guessing there's some weird rounding code going wrong. It seems that Extent and Viewport are slightly off and that's making it scroll, but I couldn't say why.
